#!/bin/bash
#=======================================================================
# setup - Setup for archibald.pl
# Copyright (C) 2012  Dag Robøle
# 
# This program is free software; you can redistribute it and/or
# modify it under the terms of the GNU General Public License
# as published by the Free Software Foundation; either version 2
# of the License, or (at your option) any later version.
# 
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
# 
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.
#=======================================================================

if [[ $EUID -ne 0 ]]; then
   echo "This script must be run as root" 1>&2
   exit 1
fi

which pacman > /dev/null 2>&1
if [ "$?" -ne "0" ]
then
    echo 'pacman does not appear to be installed. Exiting...'
    exit 1
fi

function install_package
{
    pacman -Qs $1 > /dev/null 2>&1    
    if [ "$?" -ne "0" ]
    then
        echo "Installing $1..."
        pacman -S --noconfirm $1 > /dev/null 2>&1        
        if [ "$?" -ne "0" ]
        then
            if [ "$2" -ne "0" ]
            then
                echo "Installation of required package $1 failed. Exiting..."
                exit 1
            else
                echo "Installation of package $1 failed. Some functionality in archibald may be unavailable!"
            fi
        fi
    else
        echo "$1 already installed."
    fi    
}

echo "Installing prerequisites, please wait..."

install_package perl-curses 1
install_package perl-curses-ui 1

exec ./archibald.pl
